import test from 'node:test';import assert from 'node:assert/strict';import {fixture,cookie} from './fixtures.mjs';import {identity} from '../src/lib/cookies.js';
const f=fixture();globalThis.chrome=f.api;await import('../src/background/worker.js');
const send=m=>new Promise(resolve=>f.api.runtime.onMessage.listeners[0](m,{id:'test',url:'chrome-extension://test/src/options/index.html'},resolve));
function reset(list,whitelist=[]){f.setCookies(list);f.setWhitelist(whitelist);f.calls.length=0;}
for(const target of [cookie(),cookie({hostOnly:false,domain:'.before.test',path:'/account',secure:false,httpOnly:false,sameSite:'strict',session:false,expirationDate:2000000000}),cookie({storeId:'1',partitionKey:{topLevelSite:'https://top.test',hasCrossSiteAncestor:true}})])test(`individual worker deletion exact selection ${identity(target)}`,async()=>{const other=cookie({name:'other'});reset([target,other]);const response=await send({type:'delete-cookie',host:'before.test',id:identity(target)});assert.equal(response.ok,true);assert.equal(response.data.deleted,1);assert.deepEqual(f.cookies,[other]);assert.equal(f.calls.length,1);const d=f.calls[0];assert.equal(d.name,target.name);assert.equal(d.storeId,target.storeId);assert.equal(d.url,`${target.secure?'https':'http'}://before.test${target.path}`);assert.deepEqual(d.partitionKey,target.partitionKey);const snapshot=(await send({type:'snapshot'})).data;assert.equal(snapshot.total,1);assert.equal(snapshot.rows[0].count,1);assert.equal(snapshot.state.history[0].deleted,1);assert.ok(!JSON.stringify(snapshot.state.history).includes('SYNTHETIC'));});
test('individual worker deletion leaves empty domain and updates total/history',async()=>{const target=cookie();reset([target]);const r=await send({type:'delete-cookie',host:'before.test',id:identity(target)});assert.equal(r.data.deleted,1);const s=(await send({type:'snapshot'})).data;assert.equal(s.total,0);assert.equal(s.totalBytes,0);assert.deepEqual(s.rows,[]);});
test('missing cookie and mismatched domain fail safe',async()=>{reset([]);assert.equal((await send({type:'delete-cookie',host:'before.test',id:identity(cookie())})).data.missing,true);reset([cookie()]);assert.equal((await send({type:'delete-cookie',host:'other.test',id:identity(cookie())})).ok,false);assert.equal(f.calls.length,0);});
test('current whitelist wins over individual confirmation and metadata hides values',async()=>{reset([cookie()],['before.test']);const details=(await send({type:'details',host:'before.test'})).data;assert.equal(details[0].protected,true);assert.ok(!JSON.stringify(details).includes('SYNTHETIC'));const r=await send({type:'delete-cookie',host:'before.test',id:identity(cookie())});assert.equal(r.data.deleted,0);assert.equal(f.calls.length,0);});
test('single target refuses unapproved same-name collateral',async()=>{const target=cookie({path:'/account'}),collateral=cookie({path:'/'});reset([target,collateral]);const r=await send({type:'delete-cookie',host:'before.test',id:identity(target)});assert.equal(r.data.deleted,0);assert.equal(f.calls.length,0);assert.equal(f.cookies.length,2);});
test('chrome remove error keeps cookie and returns failed aggregate without values',async()=>{const target=cookie();reset([target]);const original=f.api.cookies.remove;f.api.cookies.remove=async()=>{throw new Error('synthetic failure');};try{const r=await send({type:'delete-cookie',host:'before.test',id:identity(target)});assert.equal(r.data.failed,1);assert.equal(r.data.deleted,0);assert.equal(f.cookies.length,1);assert.ok(!JSON.stringify(r).includes('SYNTHETIC'));}finally{f.api.cookies.remove=original;}});
