import test from 'node:test';import assert from 'node:assert/strict';
import {createCookieList,cookieDetails} from '../src/lib/cookie-list.js';
import {cookie} from './fixtures.mjs';import {metadata,identity} from '../src/lib/cookies.js';
class Element{constructor(tag){this.tagName=tag;this.children=[];this.textContent='';this.hidden=false;}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}setAttribute(key,value){this[key]=value;}}
const all=el=>[el,...el.children.flatMap(all)];
function setup(initial){let cookies=initial,updates=0,result={deleted:1};const calls=[];globalThis.document={createElement:tag=>new Element(tag),getElementById:()=>new Element('p')};globalThis.confirm=()=>true;globalThis.chrome={runtime:{sendMessage:async m=>{calls.push(m);if(m.type==='details')return {ok:true,data:cookies};if(result.error)throw new Error('API error');if(result.deleted===1)cookies=cookies.filter(c=>identity(c)!==m.id);return {ok:true,data:result};}}};const list=createCookieList('before.test',async()=>{updates++;});return {list,calls,setResult:r=>result=r,get updates(){return updates;},get cookies(){return cookies;}};}
for(const n of [0,1,150])test(`site list with ${n} cookies is compact, name-sorted and hides values`,async()=>{const f=setup(Array.from({length:n},(_,i)=>({...metadata(cookie({name:`cookie${String(n-i).padStart(3,'0')}`})),value:'MUST_NOT_RENDER'})));await f.list.load();const nodes=all(f.list.element);assert.equal(nodes.filter(n=>n.tagName==='pre').length,n);assert.ok(nodes.filter(n=>n.tagName==='pre').every(n=>n.hidden&&n.textContent===''));assert.ok(!JSON.stringify(f.list.element).includes('MUST_NOT_RENDER'));if(n){const names=nodes.filter(n=>n.tagName==='strong').map(n=>n.textContent);assert.deepEqual(names,[...names].sort());}else assert.ok(nodes.some(n=>n.textContent==='Este dominio no tiene cookies.'));});
test('View expands only selected cookie metadata and never value',async()=>{const a=metadata(cookie()),b=metadata(cookie({name:'second',partitionKey:{topLevelSite:'https://top.test',hasCrossSiteAncestor:true}}));const f=setup([{...a,value:'PRIVATE_SYNTHETIC'},b]);await f.list.load();const views=all(f.list.element).filter(n=>n.tagName==='button'&&n.textContent==='Ver');await views[1].onclick();const pres=all(f.list.element).filter(n=>n.tagName==='pre');assert.equal(pres[0].hidden,true);assert.equal(pres[0].textContent,'');assert.equal(pres[1].hidden,false);assert.ok(pres[1].textContent.includes('partitionKey'));assert.ok(!pres[1].textContent.includes('value'));assert.ok(!JSON.stringify(cookieDetails({...a,value:'PRIVATE_SYNTHETIC'})).includes('PRIVATE_SYNTHETIC'));await views[1].onclick();assert.equal(pres[1].hidden,true);});
test('Delete confirms selected metadata, removes row and refreshes dashboard totals down to zero',async()=>{const a=metadata(cookie()),b=metadata(cookie({name:'second'}));const f=setup([a,b]);const prompts=[];globalThis.confirm=text=>{prompts.push(text);return true;};await f.list.load();await all(f.list.element).find(n=>n.tagName==='button'&&n.textContent==='Borrar').onclick();assert.equal(f.updates,1);assert.equal(f.cookies.length,1);assert.equal(f.calls.find(c=>c.type==='delete-cookie').id,identity(a));assert.ok(prompts[0].includes('Cookie: old'));assert.ok(!prompts[0].includes('SYNTHETIC'));assert.match(f.list.element.children[0].textContent,/1 cookies/);await all(f.list.element).find(n=>n.tagName==='button'&&n.textContent==='Borrar').onclick();assert.equal(f.updates,2);assert.equal(f.cookies.length,0);assert.match(f.list.element.children[0].textContent,/0 cookies · 0 B/);});
test('Cancel confirmation and protected cookies do not send deletion requests',async()=>{const f=setup([metadata(cookie())]);await f.list.load();globalThis.confirm=()=>false;await all(f.list.element).find(n=>n.textContent==='Borrar').onclick();assert.ok(!f.calls.some(c=>c.type==='delete-cookie'));const p=setup([{...metadata(cookie()),protected:true}]);await p.list.load();const button=all(p.list.element).find(n=>n.textContent==='Borrar');assert.equal(button.disabled,true);await button.onclick();assert.ok(!p.calls.some(c=>c.type==='delete-cookie'));});
for(const result of [{deleted:0,missing:true},{deleted:0,failed:1},{error:true}])test(`individual deletion safe result ${JSON.stringify(result)}`,async()=>{const f=setup([metadata(cookie())]);f.setResult(result);await f.list.load();await all(f.list.element).find(n=>n.textContent==='Borrar').onclick();assert.equal(f.cookies.length,1);assert.ok(f.list.element.children[1].textContent.length>0);assert.ok(!JSON.stringify(f.list.element).includes('SYNTHETIC'));});
