import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,cookie,event} from './fixtures.mjs';import {readState,saveState} from '../src/lib/storage.js';
import {watchLastNormalWindow} from '../src/lib/last-window.js';import {validateSchedule} from '../src/lib/schedule.js';
function windowsFixture(windows){let current=windows;const api={windows:{getAll:async()=>current,onCreated:event(),onRemoved:event()}};return {api,set:list=>current=list,remove:async id=>{for(const fn of api.windows.onRemoved.listeners)await fn(id);},create:w=>{current.push(w);api.windows.onCreated.emit(w);}};}
test('migration keeps interval but persists one schedule; invalid configuration fails closed',async()=>{let state={whitelist:[],interval:4320,nextRun:123,history:[]};const api={storage:{local:{get:async()=>({state}),set:async data=>state=data.state}}};const s=await readState(api);assert.deepEqual(s.cleanupSchedule,{mode:'interval',interval:4320});await saveState(api,s);assert.equal('interval' in state,false);state.cleanupSchedule={mode:'lastWindowClosed'};state.nextRun=123;assert.equal((await readState(api)).nextRun,null);for(const schedule of [{mode:'invalid'},{mode:'interval',interval:1}])assert.throws(()=>validateSchedule(schedule));});
test('last-window watcher ignores popup, auxiliary and non-last normal removal; fires once per last normal closure',async()=>{const w=windowsFixture([{id:1,type:'normal'},{id:2,type:'normal'},{id:3,type:'popup'}]);let calls=0;watchLastNormalWindow(w.api,async()=>calls++);await Promise.resolve();await w.remove(999);assert.equal(calls,0);w.set([{id:1,type:'normal'},{id:2,type:'normal'}]);await w.remove(3);assert.equal(calls,0);w.set([{id:2,type:'normal'}]);await w.remove(1);assert.equal(calls,0);w.set([]);await w.remove(2);await w.remove(2);assert.equal(calls,1);w.create({id:4,type:'normal'});w.set([]);await w.remove(4);assert.equal(calls,2);});
const f=fixture();const w=windowsFixture([{id:10,type:'normal'},{id:11,type:'popup'}]);f.api.windows=w.api.windows;globalThis.chrome=f.api;await import('../src/background/worker.js');const send=m=>new Promise(resolve=>f.api.runtime.onMessage.listeners[0](m,{id:'test',url:'chrome-extension://test/src/options/index.html'},resolve));
test('visible schedule settings persist last-window mode, clear alarm and safely clean current cookies once',async()=>{f.setCookies([cookie(),cookie({domain:'protected.test'})]);f.setWhitelist(['protected.test']);let p=(await send({type:'preview'})).data;assert.equal((await send({type:'settings',schedule:{mode:'interval',interval:1440},token:p.token})).ok,true);assert.ok(await f.api.alarms.get());p=(await send({type:'preview'})).data;assert.equal((await send({type:'settings',schedule:{mode:'lastWindowClosed'},token:p.token})).ok,true);assert.deepEqual(f.state.cleanupSchedule,{mode:'lastWindowClosed'});assert.equal('interval' in f.state,false);assert.equal(f.state.nextRun,null);assert.equal(await f.api.alarms.get(),undefined);w.set([{id:10,type:'normal'}]);await w.remove(11);assert.equal(f.calls.length,0);w.set([]);await w.remove(10);await w.remove(10);assert.equal(f.calls.length,1);assert.deepEqual(f.cookies.map(c=>c.domain),['protected.test']);assert.equal(f.state.history[0].source,'automatic');assert.equal(f.state.history[0].deleted,1);});
test('last normal closure does not clean for disabled/interval modes',async()=>{for(const schedule of [{mode:'disabled'},{mode:'interval',interval:4320}]){w.create({id:20,type:'normal'});const p=(await send({type:'preview'})).data;await send({type:'settings',schedule,token:p.token});const before=f.calls.length;w.set([]);await w.remove(20);assert.equal(f.calls.length,before);}});

test('worker restart restores normal IDs without URLs and duplicate terminal removal remains blocked',async()=>{let saved={};const w=windowsFixture([{id:31,type:'normal'}]);w.api.storage={session:{get:async()=>saved,set:async data=>Object.assign(saved,structuredClone(data))}};let count=0;const stop=watchLastNormalWindow(w.api,async()=>count++);for(let i=0;i<5;i++)await Promise.resolve();stop();w.set([]);const stop2=watchLastNormalWindow(w.api,async()=>count++);await w.remove(31);assert.equal(count,1);assert.deepEqual(saved.lastNormalWindowState,{ids:[],fired:true});assert.ok(!JSON.stringify(saved).includes('url'));stop2();watchLastNormalWindow(w.api,async()=>count++);await w.remove(31);assert.equal(count,1);});
test('closing last normal during another cleanup does not start a second job',async()=>{f.setCookies([cookie()]);f.setWhitelist([]);w.create({id:40,type:'normal'});let p=(await send({type:'preview'})).data;await send({type:'settings',schedule:{mode:'lastWindowClosed'},token:p.token});p=(await send({type:'preview'})).data;const original=f.api.cookies.remove;let started,release;const began=new Promise(resolve=>started=resolve),gate=new Promise(resolve=>release=resolve);f.api.cookies.remove=async d=>{started();await gate;return original(d);};try{const cleaning=send({type:'clean',host:null,token:p.token});await began;w.set([]);await w.remove(40);release();const r=await cleaning;assert.equal(r.data.deleted,1);assert.equal(f.state.history[0].source,'manual');}finally{release();f.api.cookies.remove=original;}});

test('automatic configuration transitions need no preview/token and never run cleanup immediately',async()=>{const before=f.calls.length,history=f.state.history.length;for(const schedule of [{mode:'interval',interval:1440},{mode:'lastWindowClosed'},{mode:'interval',interval:10080},{mode:'disabled'}]){const r=await send({type:'settings',schedule,token:'invalid-not-consulted'});assert.equal(r.ok,true);assert.deepEqual(f.state.cleanupSchedule,schedule);assert.equal(f.calls.length,before);assert.equal(f.state.history.length,history);const alarm=await f.api.alarms.get();assert.equal(!!alarm,schedule.mode==='interval');}});
test('last-window automatic cleanup uses newly created cookies and newly protected sites without any preview',async()=>{f.setCookies([cookie()]);f.setWhitelist([]);w.create({id:50,type:'normal'});assert.equal((await send({type:'settings',schedule:{mode:'lastWindowClosed'}})).ok,true);f.add(cookie({domain:'new.test',name:'new'}));f.setWhitelist(['before.test']);const before=f.calls.length;w.set([]);await w.remove(50);assert.equal(f.calls.length,before+1);assert.deepEqual(f.cookies.map(c=>c.domain),['before.test']);assert.equal(f.state.history[0].source,'automatic');assert.equal(f.state.history[0].deleted,1);});
test('settings never consumes a manual preview; manual cleanup still intersects and expiry stays specific',async()=>{f.setWhitelist([]);f.setCookies([cookie()]);const p=(await send({type:'preview'})).data;assert.equal((await send({type:'settings',schedule:{mode:'lastWindowClosed'},token:p.token})).ok,true);f.add(cookie({domain:'after.test',name:'new'}));const r=await send({type:'clean',token:p.token,host:null});assert.equal(r.data.deleted,1);assert.deepEqual(f.cookies.map(c=>c.domain),['after.test']);assert.equal((await send({type:'clean',token:'invalid',host:null})).ok,false);const expired=(await send({type:'preview'})).data;const now=Date.now;Date.now=()=>now()+600001;try{const response=await send({type:'clean',token:expired.token,host:null});assert.equal(response.ok,false);assert.equal(response.error,'La vista previa ha caducado. Genera una nueva antes de continuar.');}finally{Date.now=now;}const bad=await send({type:'settings',schedule:{mode:'unknown'}});assert.equal(bad.ok,false);assert.equal(bad.error,'No se pudo guardar la configuración de limpieza automática.');assert.ok(!bad.error.includes('vista previa'));});
