import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
class Element{constructor(){this.children=[];this.listeners={};this.textContent='';this.value='';}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}dispatch(name){for(const fn of this.listeners[name]??[])fn();}showModal(){this.open=true;}close(){this.open=false;}}
const all=el=>[el,...el.children.flatMap(all)];const tick=()=>new Promise(resolve=>setImmediate(resolve));let serial=0;
async function setup(n,{prefs,permission=true}={}){
 const html=readFileSync('src/options/index.html','utf8'),elements=new Map([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element()]));const get=id=>elements.get(id);globalThis.document={getElementById:get,createElement:()=>new Element()};get('filter').value='all';get('page-size').value='50';
 let whitelist=[],preferences=prefs;const calls=[],prefWrites=[];const rows=Array.from({length:n},(_,i)=>({domain:`site${String(i).padStart(4,'0')}.test`,count:i+1,bytes:i,protectedCookies:0}));
 const send=async m=>{calls.push(m);let data;if(m.type==='status')data={state:'idle'};else if(m.type==='preview')data={token:'qa',remove:n,keep:0,affectedDomains:['synthetic.test'],keptDomains:[],protectedSites:[],approximateBytes:100,protectedCookies:0,temporalExcluded:0,candidates:[{name:'snapshot_only',domain:'synthetic.test',path:'/scope',session:true,storeId:'0',approximateBytes:42,value:'SYNTHETIC_NOT_FOR_DISPLAY',partitionKey:{topLevelSite:'https://top.test',hasCrossSiteAncestor:true}}]};else if(m.type==='clean')data={deleted:n,skipped:0,failed:0};else if(m.type==='protect-list'){const unique=[...new Set(m.hosts)],added=unique.filter(h=>!whitelist.includes(h));whitelist=[...new Set([...whitelist,...unique])];data={added:added.length,alreadyProtected:unique.length-added.length};}else data={rows,state:{whitelist,history:[],cleanupSchedule:{mode:'disabled'}},total:n,totalBytes:100,preview:{remove:n},running:false};return {ok:true,data};};
 globalThis.chrome={runtime:{getManifest:()=>({version:'9.8.7'}),sendMessage:send},storage:{local:{get:async()=>({dashboardPreferences:preferences}),set:async data=>{preferences=data.dashboardPreferences;prefWrites.push(preferences);}},onChanged:{addListener(){}}},permissions:{contains:async()=>permission,request:async()=>permission,onRemoved:{addListener(){}}},history:{search:async()=>rows.map(r=>({url:`https://${r.domain}/synthetic`})),getVisits:async({url})=>[{visitId:url,visitTime:Date.now()-86400000,transition:'link'}],onVisited:{addListener(){}},onVisitRemoved:{addListener(){}}}};
 await import(`../src/options/options.js?bulk-test=${serial++}`);for(let i=0;i<8;i++)await tick();
 const visible=()=>get('rows').children.map(row=>row.children[0].children[0].textContent);
 const protect=async()=>{get('protect-list').onclick();await all(get('dialog-actions')).find(e=>e.textContent==='Proteger sitios').onclick();};
 return {get,calls,visible,protect,prefWrites,setWhitelist:list=>whitelist=list,get whitelist(){return whitelist;}};
}
for(const [n,size,expected] of [[0,'50',0],[1,'50',1],[1050,'50',50],[1050,'100',100],[1050,'all',1050]])test(`bulk UI ${n} rows/page ${size}: protects exactly rendered collection`,async()=>{const f=await setup(n);f.get('page-size').value=size;f.get('page-size').dispatch('input');const visible=f.visible();assert.equal(visible.length,expected);assert.equal(f.get('protect-list').disabled,!expected);if(!expected)return;await f.protect();const call=f.calls.find(m=>m.type==='protect-list');assert.deepEqual(call.hosts,visible);assert.equal(f.whitelist.length,expected);assert.ok(!f.calls.some(m=>m.type==='preview'||m.type==='clean'||m.type==='settings'));assert.match(f.get('notice').textContent,/sitios añadidos/);});
test('bulk UI page 2/search/filter protect only visible domains, refresh metrics and remove newly protected from filter',async()=>{const f=await setup(205);f.get('page-next').onclick();const page2=f.visible();await f.protect();assert.deepEqual(f.whitelist,page2);assert.ok(!f.whitelist.includes('site0000.test'));f.get('filter').value='unprotected';f.get('filter').dispatch('input');f.get('search').value='site00';f.get('search').dispatch('input');const filtered=f.visible();assert.equal(filtered.length,50);await f.protect();assert.ok(filtered.every(h=>f.whitelist.includes(h)));assert.ok(f.visible().every(h=>!filtered.includes(h)));const metrics=f.get('metrics').children.find(card=>card.children[0].textContent==='Sitios protegidos');assert.equal(metrics.children[1].textContent,'100');f.get('filter').value='protected';f.get('filter').dispatch('input');const protectedVisible=f.visible();await f.protect();assert.ok(protectedVisible.every(h=>f.whitelist.includes(h)));assert.match(f.get('notice').textContent,/0 sitios añadidos/);});
test('bulk UI confirmation freezes the visible page and Cancel makes no change',async()=>{const f=await setup(101);f.get('protect-list').onclick();assert.match(f.get('dialog-title').textContent,/50 sitios/);all(f.get('dialog-actions')).find(e=>e.textContent==='Cancelar').onclick();assert.equal(f.whitelist.length,0);const before=f.visible();f.get('protect-list').onclick();f.get('page-next').onclick();await all(f.get('dialog-actions')).find(e=>e.textContent==='Proteger sitios').onclick();assert.deepEqual(f.whitelist,before);});
test('dashboard defaults visits/7 days, no history degrades; saved preference and subsequent periods remain usable',async()=>{const f=await setup(51,{permission:false});assert.equal(f.get('sort').value,'visits');assert.equal(f.get('history-period').value,'7');assert.equal(f.get('visits-heading').textContent,'Visitas últimos 7 días');assert.match(f.get('ranking-status').textContent,/historial es opcional/);assert.equal(f.visible().length,50);const saved=await setup(51,{prefs:{sort:'bytes',historyRange:'90'}});assert.equal(saved.get('sort').value,'bytes');assert.equal(saved.get('history-period').value,'90');saved.get('sort').value='visits';saved.get('sort').dispatch('input');for(const range of ['7','30','90','all']){saved.get('history-period').value=range;saved.get('history-period').dispatch('input');for(let i=0;i<6;i++)await tick();assert.ok(saved.get('visits-heading').textContent.includes(range==='all'?'todo':range));const visible=saved.visible();await saved.protect();assert.deepEqual(saved.calls.filter(c=>c.type==='protect-list').at(-1).hosts,visible);}assert.equal(saved.prefWrites.at(-1).historyRange,'all');});

for(const hours of ['1','2','24'])test(`recent UI dry/clean use ${hours} hours; full ignores selector and refresh never cleans`,async()=>{
 const f=await setup(1);f.get('recent-hours').value=hours;const before=f.calls.length;await f.get('dry').onclick();let calls=f.calls.slice(before);assert.equal(calls.find(m=>m.type==='preview').recentHours,Number(hours));assert.ok(!calls.some(m=>m.type==='clean'));await f.get('clean').onclick();await all(f.get('dialog-actions')).find(e=>e.textContent==='Limpiar cookies recientes').onclick();assert.equal(f.calls.filter(m=>m.type==='clean').at(-1).recentHours,Number(hours));
 const count=f.calls.filter(m=>m.type==='clean').length;await f.get('clean-all').onclick();assert.equal(f.get('dialog-title').textContent,'Limpieza completa');assert.equal(f.calls.filter(m=>m.type==='clean').length,count);assert.equal(f.calls.filter(m=>m.type==='preview').at(-1).recentHours,null);await all(f.get('dialog-actions')).find(e=>e.textContent==='Cancelar').onclick();assert.equal(f.calls.filter(m=>m.type==='clean').length,count);
 await f.get('clean-all').onclick();await all(f.get('dialog-actions')).find(e=>e.textContent==='Limpiar todas las no protegidas').onclick();assert.equal(f.calls.filter(m=>m.type==='clean').at(-1).recentHours,null);const refreshBefore=f.calls.length;await f.get('refresh').onclick();assert.ok(!f.calls.slice(refreshBefore).some(m=>m.type==='clean'||m.type==='preview'));
});

for(const operation of ['dry','clean','clean-all'])test(operation+': detail uses original candidates, hides values and returns without losing token or range',async()=>{
 const f=await setup(1);f.get('recent-hours').value='2';await f.get(operation).onclick();const before=f.calls.length,title=f.get('dialog-title').textContent;
 const link=all(f.get('dialog-body')).find(e=>e.textContent==='Ver cookies que se eliminarán');assert.ok(link);await link.onclick();
 const text=all(f.get('dialog-body')).map(e=>e.textContent).join(' ');assert.ok(text.includes('snapshot_only')&&text.includes('/scope')&&text.includes('top.test'));assert.ok(!text.includes('SYNTHETIC_NOT_FOR_DISPLAY')&&!text.includes('"value"'));assert.equal(f.calls.length,before);
 await all(f.get('dialog-actions')).find(e=>e.textContent==='Volver al resumen').onclick();assert.equal(f.get('dialog-title').textContent,title);assert.equal(f.calls.length,before);assert.equal(f.get('recent-hours').value,'2');
 if(operation!=='dry'){await all(f.get('dialog-actions')).find(e=>e.textContent===(operation==='clean'?'Limpiar cookies recientes':'Limpiar todas las no protegidas')).onclick();const clean=f.calls.filter(m=>m.type==='clean').at(-1);assert.equal(clean.token,'qa');assert.equal(clean.recentHours,operation==='clean'?2:null);}
 else assert.ok(!f.calls.some(m=>m.type==='clean'));
});
