import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {fixture,cookie} from './fixtures.mjs';import {createRecentCookies} from '../src/lib/recent-cookies.js';
import {identity} from '../src/lib/cookies.js';
test('dashboard header has only Refresh; two independent cards contain schedule controls and ordered manual actions',()=>{const html=readFileSync('src/options/index.html','utf8'),header=html.split('<header>')[1].split('</header>')[0];assert.deepEqual([...header.matchAll(/<button id="([^"]+)"/g)].map(m=>m[1]),['refresh']);const box=html.split('class="cleanup-columns"')[1].split('<p id="notice"')[0];assert.equal((box.match(/class="card cleanup-column"/g)||[]).length,2);assert.ok(!box.includes('Limpiar ahora'));assert.ok(box.includes('Limpiar selección'));assert.ok(box.indexOf('id="dry"')<box.indexOf('id="clean"')&&box.indexOf('id="clean"')<box.indexOf('id="clean-all"'));for(const id of ['interval','settings','recent-hours','dry','clean','clean-all'])assert.ok(box.includes(`id="${id}"`));for(const value of ['0','1440','4320','10080','lastWindowClosed'])assert.ok(box.includes(`value="${value}"`));assert.ok(box.includes('Limpieza reciente'));});
test('observations use change time only, restore fingerprints, expire and never store values/names/domains',async()=>{let now=100000000,saved={};const api={storage:{session:{get:async()=>saved,set:async data=>Object.assign(saved,structuredClone(data))}}};const tracker=createRecentCookies(api,()=>now);const c=cookie({name:'PRIVATE_NAME_TEST',domain:'private.test'}),unknown=cookie({name:'unknown'});try{assert.equal((await tracker.eligible([c],1)).size,0);await tracker.observe({cookie:c,removed:false});await tracker.flush();const json=JSON.stringify(saved);assert.ok(!json.includes('SYNTHETIC')&&!json.includes('PRIVATE_NAME_TEST')&&!json.includes('private.test'));const restored=createRecentCookies(api,()=>now);try{assert.deepEqual(await restored.eligible([c,unknown],1),new Set([identity(c)]));now+=2*3600000;assert.equal((await restored.eligible([c],1)).size,0);assert.equal((await restored.eligible([c],24)).size,1);await restored.observe({cookie:c,removed:true});assert.equal((await restored.eligible([c],24)).size,0);}finally{restored.stop();}}finally{tracker.stop();}});
const f=fixture();globalThis.chrome=f.api;await import('../src/background/worker.js');const send=m=>new Promise(resolve=>f.api.runtime.onMessage.listeners[0](m,{id:'test',url:'chrome-extension://test/src/options/index.html'},resolve));
async function seed(){const original=Date.now;let at=original();Date.now=()=>at;const a=cookie({name:'a'}),b=cookie({name:'b'}),c=cookie({name:'c'}),unknown=cookie({name:'unknown',expirationDate:original()/1000+10000}),protectedCookie=cookie({name:'protected',domain:'protected.test'});f.setWhitelist(['protected.test']);f.setCookies([a,b,c,unknown,protectedCookie]);try{for(const [target,age] of [[a,.5],[b,1.5],[c,23],[protectedCookie,.5]]){at=original()-age*3600000;f.api.cookies.onChanged.emit({cookie:target,removed:false,cause:'explicit'});}at=original();return {a,b,c,unknown,protectedCookie};}finally{Date.now=original;}}
for(const [hours,n] of [[1,1],[2,2],[24,3]])test(`recent worker ${hours}h preview does not delete; confirmation deletes only observed authorized and unprotected`,async()=>{const targets=await seed();const calls=f.calls.length;const p=(await send({type:'preview',recentHours:hours})).data;assert.equal(p.remove,n);assert.equal(f.calls.length,calls);f.add(cookie({name:'new'}));const r=await send({type:'clean',token:p.token,host:null,recentHours:hours});assert.equal(r.ok,true);assert.equal(r.data.deleted,n);assert.ok(f.cookies.some(c=>c.name==='unknown'));assert.ok(f.cookies.some(c=>c.name==='protected'));assert.ok(f.cookies.some(c=>c.name==='new'));});
test('recent confirmation uses current whitelist and rejects scope widening to full',async()=>{await seed();const p=(await send({type:'preview',recentHours:1})).data;assert.equal((await send({type:'clean',token:p.token,host:null})).ok,false);f.setWhitelist(['before.test','protected.test']);const r=await send({type:'clean',token:p.token,host:null,recentHours:1});assert.equal(r.data.deleted,0);});
test('full preview includes unknown-age inventory, preserves protected and requires valid confirmation token',async()=>{await seed();assert.equal((await send({type:'clean',token:'invalid',host:null})).ok,false);const p=(await send({type:'preview'})).data;assert.equal(p.remove,4);const r=await send({type:'clean',token:p.token,host:null});assert.equal(r.data.deleted,4);assert.deepEqual(f.cookies.map(c=>c.name),['protected']);});
