// Optional real-browser smoke test. A new disposable Edge profile is mandatory.
// Pass a locally installed Playwright index.mjs path as the first argument.
import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const {chromium}=process.argv[2]?await import(pathToFileURL(resolve(process.argv[2])).href):await import('playwright');
const root=process.cwd(),profile=await mkdtemp(join(tmpdir(),'cookiekeep-qa-'));
const executable=join(process.env['ProgramFiles(x86)']||'C:/Program Files (x86)','Microsoft/Edge/Application/msedge.exe');
let context;
try{
 context=await chromium.launchPersistentContext(profile,{executablePath:executable,headless:true,args:[`--disable-extensions-except=${root}`,`--load-extension=${root}`]});
 let [worker]=context.serviceWorkers();if(!worker)worker=await context.waitForEvent('serviceworker',{timeout:10000});
 const id=new URL(worker.url()).hostname,page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`chrome-extension://${id}/src/options/index.html`);
 assert.deepEqual(await page.locator('main>header button').allTextContents(),['Actualizar']);assert.equal(await page.locator('.cleanup-columns > section.card.cleanup-column').count(),2);
 for(const card of await page.locator('.cleanup-columns > section.card').all())assert.ok(await card.evaluate(el=>parseFloat(getComputedStyle(el).borderTopWidth)>0 && parseFloat(getComputedStyle(el).paddingLeft)>0));
 assert.equal(await page.locator('#sort').inputValue(),'visits');assert.equal(await page.locator('#history-period').inputValue(),'7');await page.waitForFunction(()=>document.querySelector('#visits-heading').textContent==='Visitas últimos 7 días');
 const send=async message=>{const r=await page.evaluate(m=>chrome.runtime.sendMessage(m),message);assert.equal(r.ok,true);return r.data;};
 const set=details=>page.evaluate(d=>chrome.cookies.set({...d,value:'SYNTHETIC_QA_ONLY'}),details);
 const get=domain=>page.evaluate(d=>chrome.cookies.getAll({domain:d,partitionKey:{}}),domain);
 const base={name:'ck_qa_sid',path:'/',secure:false,sameSite:'lax'};
 await set({...base,url:'http://protected.test/'});await set({...base,url:'http://tracker.test/'});await send({type:'toggle',host:'protected.test'});
 for(const hours of ['1','2','24']){const before=(await get('tracker.test')).length;await page.selectOption('#recent-hours',hours);await page.click('#dry');await page.waitForFunction(()=>document.querySelector('#dialog').open);assert.equal((await get('tracker.test')).length,before);await page.getByRole('button',{name:'Cerrar',exact:true}).click();}
 const p=await send({type:'preview',host:'tracker.test'});assert.equal(p.remove,1);
 await set({...base,name:'ck_qa_new',url:'http://tracker.test/'});
 const result=await send({type:'clean',host:'tracker.test',token:p.token});assert.equal(result.deleted,1);assert.ok((await get('protected.test')).some(c=>c.name==='ck_qa_sid'));assert.deepEqual((await get('tracker.test')).map(c=>c.name),['ck_qa_new']);
 await page.click('#refresh');
 await page.getByRole('button',{name:'tracker.test',exact:true}).click();
 assert.equal(await page.locator('.cookie-row').count(),1);
 assert.ok(await page.locator('.cookie-detail').isHidden());
 await page.locator('.cookie-row').getByRole('button',{name:'Ver',exact:true}).click();
 const detail=await page.locator('.cookie-detail').textContent();assert.ok(detail.includes('ck_qa_new'));assert.ok(!detail.includes('SYNTHETIC_QA_ONLY'));assert.ok(!detail.includes('"value"'));
 page.once('dialog',dialog=>dialog.accept());await page.locator('.cookie-row').getByRole('button',{name:'Borrar',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.cookie-list-rows').textContent.includes('Este dominio no tiene cookies.'));
 assert.equal((await get('tracker.test')).length,0);await page.getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.getByRole('button',{name:'protected.test',exact:true}).click();assert.ok(await page.locator('.cookie-row').getByRole('button',{name:'Borrar',exact:true}).isDisabled());await page.getByRole('button',{name:'Cerrar',exact:true}).click();
 await set({...base,url:'http://example.test/',domain:'.example.test'});await set({...base,url:'http://sub.example.test/'});await send({type:'toggle',host:'example.test'});
 assert.equal((await send({type:'preview',host:'sub.example.test'})).remove,0);
 await set({...base,name:'ck_qa_path',url:'https://paths.test/account',path:'/account',secure:true});
 const pathPreview=await send({type:'preview',host:'paths.test'});await set({...base,name:'ck_qa_path',url:'https://paths.test/',secure:true});
 assert.equal((await send({type:'clean',host:'paths.test',token:pathPreview.token})).deleted,0);
 await set({url:'https://chips.test/',name:'ck_qa_chips',secure:true,sameSite:'no_restriction',partitionKey:{topLevelSite:'https://top.test',hasCrossSiteAncestor:true}});
 await send({type:'toggle',host:'top.test'});assert.equal((await send({type:'preview',host:'chips.test'})).remove,0);
 await send({type:'toggle',host:'top.test'});const cp=await send({type:'preview',host:'chips.test'});assert.equal(cp.remove,1);assert.equal((await send({type:'clean',host:'chips.test',token:cp.token})).deleted,1);
 const status=await send({type:'status'});assert.equal(status.state,'completed');
 // Start a longer real job, destroy the initiating UI, and inspect it from a
 // new popup. Only this temporary profile contains these synthetic targets.
 for(let offset=0;offset<1000;offset+=8)await Promise.all(Array.from({length:Math.min(8,1000-offset)},(_,i)=>set({url:`https://qa${offset+i}.test/`,name:`ck_qa_bulk_${offset+i}`,secure:true,sameSite:'lax'})));
 const bulk=await send({type:'preview'});await page.evaluate(token=>{chrome.runtime.sendMessage({type:'clean',host:null,token}).catch(()=>{});},bulk.token);
 let active;for(let attempt=0;attempt<20;attempt++){active=await send({type:'status'});if(active.state==='running')break;}assert.equal(active.state,'running');
 await page.close();const reopened=await context.newPage();await reopened.goto(`chrome-extension://${id}/src/popup/index.html`);await reopened.waitForFunction(()=>document.querySelector('#cleanup-progress-label').textContent==='Eliminando cookies…');assert.ok(await reopened.locator('#delete').isDisabled());
 const recovered=await reopened.evaluate(()=>chrome.runtime.sendMessage({type:'status'}));assert.equal(recovered.data.state,'running');
 await reopened.click('#cancel-cleanup');await reopened.waitForFunction(()=>document.querySelector('#cleanup-progress').hidden && document.querySelector('#notice').textContent.includes('resumen parcial'),{},{timeout:10000});
 await reopened.reload();assert.ok(await reopened.locator('#cleanup-progress').isHidden());
 const dashboard=await context.newPage();await dashboard.goto(`chrome-extension://${id}/src/options/index.html`);assert.ok(await dashboard.locator('#cleanup-progress').isHidden());await dashboard.reload();assert.ok(await dashboard.locator('#cleanup-progress').isHidden());
 const partial=await reopened.evaluate(()=>chrome.runtime.sendMessage({type:'status'}));assert.equal(partial.data.cancelled,true);assert.ok(partial.data.deleted<partial.data.total);
 const finishPreview=await dashboard.evaluate(()=>chrome.runtime.sendMessage({type:'preview'}));
 await dashboard.evaluate(token=>{chrome.runtime.sendMessage({type:'clean',host:null,token}).catch(()=>{});},finishPreview.data.token);
 await dashboard.waitForFunction(()=>!document.querySelector('#cleanup-progress').hidden);
 await reopened.waitForFunction(()=>!document.querySelector('#cleanup-progress').hidden);
 await dashboard.waitForFunction(()=>document.querySelector('#cleanup-progress').hidden,{},{timeout:30000});
 await reopened.waitForFunction(()=>document.querySelector('#cleanup-progress').hidden,{},{timeout:30000});
 for(const view of [dashboard,reopened])assert.equal(await view.locator('#cleanup-progress').evaluate(el=>el.getBoundingClientRect().height),0);
 await reopened.reload();await reopened.waitForFunction(()=>document.querySelector('#version').textContent.startsWith('v'));assert.ok(await reopened.locator('#cleanup-progress').isHidden());
 await dashboard.reload();assert.ok(await dashboard.locator('#cleanup-progress').isHidden());
 // All pages belong to this disposable profile.
 await reopened.selectOption('#interval','lastWindowClosed');
 await reopened.waitForFunction(()=>document.querySelector('#next').textContent==='Próxima limpieza: al cerrar todas las ventanas');
 await dashboard.waitForFunction(()=>document.querySelector('#interval').value==='lastWindowClosed' && document.querySelector('#next').textContent==='Próxima limpieza: al cerrar todas las ventanas');
 await dashboard.selectOption('#interval','4320');await dashboard.click('#settings');
 await reopened.waitForFunction(()=>document.querySelector('#interval').value==='4320');
 await dashboard.selectOption('#interval','lastWindowClosed');await dashboard.click('#settings');
 await reopened.waitForFunction(()=>document.querySelector('#interval').value==='lastWindowClosed' && document.querySelector('#next').textContent==='Próxima limpieza: al cerrar todas las ventanas');
 const stored=await reopened.evaluate(async()=> (await chrome.storage.local.get('state')).state);assert.deepEqual(stored.cleanupSchedule,{mode:'lastWindowClosed'});assert.equal('interval' in stored,false);
 await reopened.evaluate(async()=>{for(let i=0;i<105;i++)await chrome.cookies.set({url:`https://bulk${String(i).padStart(3,'0')}.test/`,name:'ck_qa_bulk_protect',value:'SYNTHETIC_QA_ONLY',secure:true,sameSite:'lax'});});
 await dashboard.click('#refresh');await dashboard.fill('#search','bulk');await dashboard.selectOption('#filter','unprotected');
 const visible=await dashboard.locator('#rows tr td:first-child button').allTextContents();assert.equal(visible.length,50);
 await dashboard.click('#protect-list');await dashboard.getByRole('button',{name:'Proteger sitios',exact:true}).click();await dashboard.waitForFunction(()=>document.querySelector('#notice').textContent.includes('50 sitios añadidos'));
 const whitelistAfter=(await reopened.evaluate(()=>chrome.storage.local.get('state'))).state.whitelist;assert.ok(visible.every(h=>whitelistAfter.includes(h)));assert.equal(whitelistAfter.filter(h=>h.startsWith('bulk')).length,50);
 const newVisible=await dashboard.locator('#rows tr td:first-child button').allTextContents();assert.ok(newVisible.every(h=>!visible.includes(h)));
 await dashboard.selectOption('#page-size','all');const allVisible=await dashboard.locator('#rows tr td:first-child button').allTextContents();assert.equal(allVisible.length,55);
 await dashboard.click('#protect-list');await dashboard.getByRole('button',{name:'Proteger sitios',exact:true}).click();await dashboard.waitForFunction(()=>document.querySelector('#rows').children.length===0);assert.ok(await dashboard.locator('#protect-list').isDisabled());
 await dashboard.selectOption('#history-period','90');await dashboard.selectOption('#sort','bytes');await dashboard.waitForFunction(async()=>{const p=(await chrome.storage.local.get('dashboardPreferences')).dashboardPreferences;return p?.sort==='bytes'&&p?.historyRange==='90';});await dashboard.reload();await dashboard.waitForFunction(()=>document.querySelector('#sort').value==='bytes' && document.querySelector('#history-period').value==='90');
 await dashboard.setViewportSize({width:1200,height:900});assert.equal(await dashboard.locator('.cleanup-columns').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),2);
 const actionBoxes=await Promise.all(['#dry','#clean','#clean-all'].map(selector=>dashboard.locator(selector).boundingBox()));assert.ok(actionBoxes[0].x<actionBoxes[1].x && actionBoxes[1].x<actionBoxes[2].x);assert.ok(actionBoxes.every(box=>Math.abs(box.y-actionBoxes[0].y)<1));assert.equal(await dashboard.locator('#clean').textContent(),'Limpiar selección');
 await dashboard.setViewportSize({width:400,height:900});assert.equal(await dashboard.locator('.cleanup-columns').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),1);assert.ok(await dashboard.evaluate(()=>document.documentElement.scrollWidth<=400));
 await reopened.evaluate(()=>chrome.cookies.set({url:'https://recent-ui.test/',name:'ck_qa_recent_ui',value:'SYNTHETIC_QA_ONLY',secure:true,sameSite:'lax'}));await dashboard.selectOption('#recent-hours','2');await dashboard.click('#clean');await dashboard.getByRole('button',{name:'Limpiar cookies recientes',exact:true}).click();await dashboard.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Eliminadas: 1'));
 assert.equal((await reopened.evaluate(()=>chrome.cookies.getAll({domain:'recent-ui.test'}))).length,0);
 await dashboard.click('#clean-all');await dashboard.waitForFunction(()=>document.querySelector('#dialog-title').textContent==='Limpieza completa');await dashboard.getByRole('button',{name:'Cancelar',exact:true}).click();
 await reopened.setViewportSize({width:360,height:700});assert.equal(await reopened.locator('.popup-tagline br').count(),1);assert.ok(await reopened.locator('.popup-tagline').isVisible());assert.ok(await reopened.locator('#status').isHidden());assert.ok(!(await reopened.locator('body').textContent()).includes('Solo HTTP / HTTPS'));assert.ok(await reopened.locator('.popup-tagline').evaluate(el=>{const rect=el.getBoundingClientRect(),style=getComputedStyle(el);return style.textAlign==='right' && Math.abs(rect.height-2*parseFloat(style.lineHeight))<1;}));
 const manifest=JSON.parse(await readFile('manifest.json','utf8'));assert.equal(await reopened.locator('#version').textContent(),`v${manifest.version}`);assert.deepEqual(errors,[]);
 console.log(JSON.stringify({browser:'Real headless Edge extension',version:manifest.version,profile:'disposable temporary profile',checks:['unrelated name collision','manual A+B intersection','Domain parent collateral','new same-name path collateral','CHIPS protection/removal','progress after closing initiating UI','real cancellation partial result','completion hides progress in both open pages with zero layout height','terminal reload stays hidden','compact site-cookie list with selected metadata and safe individual deletion','protected cookie action disabled','visible last-window selection and shared persistence','bidirectional popup/dashboard schedule synchronization','dashboard defaults visits/7 days','protect exactly current filtered page with modal confirmation','All protects only remaining filtered rows','restore explicit dashboard preferences','recent dry run 1/2/24 hours without deletion','independent bordered cards and ordered single-row desktop actions','two-line right-aligned popup tagline and hidden unsupported status','two-column desktop and stacked narrow layout','recent confirmation deletes observed unprotected cookie','full cleanup has separate cancelable confirmation','native CSP/manifest loading'],passed:true}));
}finally{await context?.close();}
